version: '2'
services:
    cucumberserenity-app:
        image: cucumberserenity
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cucumberserenity-postgresql:5432/cucumberserenity
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cucumberserenity-postgresql:
        extends:
            file: postgresql.yml
            service: cucumberserenity-postgresql
